### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by renanzdm** [onyx-and-iris/xair-api-python#3]
Hi, I'm trying to create an Android application where I can communicate with an X18 mixer. The objective would be to listen to certain audio channels to avoid many cables used to return headphones. Could you tell me if this is possible or if I'm slow. If so, could you give me tips on materials for this?

**Comment by onyx-and-iris** [comment]
Hello. 

This package is only concerned with setting and retrieving parameter values, there is nothing related to audio transfer. You could certainly use it to toggle different channels on/off, adjust levels and so on. Please check the [obs example](https://github.com/onyx-and-iris/xair-api-python/blob/dev/examples/xair_obs/__main__.py). There I have demonstrated toggling a channel on/off and adjusting a channels fader value.

I have no experience with Android development so you will need to investigate this yourself.

I hope that was helpful.
