### ISSUE TITLE
Real-time signal level monitor

### ISSUE THREAD

**Issue by famzah** [onyx-and-iris/xair-api-python#5]
Hello,

Is it possible to get the signal level of each channel in real-time?

I guess that polling is not the right approach because it would be slow.

Thank you.

**Comment by onyx-and-iris** [comment]
Hi. It's definitely possible using meter subscriptions but currently not implemented. [This manual](https://mediadl.musictribe.com/download/software/behringer/XAIR/X%20AIR%20Remote%20Control%20Protocol.pdf) covers it briefly. 

I suppose some type of callback interface would be appropriate here.

I can investigate this down the road but I have a few things I need to deal with first.

If you can't wait you might consider checking out [pyxair](https://github.com/shadanan/pyxair). I haven't tested it personally but it seems level subscriptions are implemented.

**Comment by famzah** [comment]
Thank you for the info. You definitely shouldn't invest more time into this because of me. I'm at a very early research stage for a project.
