### ISSUE TITLE
Performance and real-time API call

### ISSUE THREAD

**Issue by rey0bs** [onyx-and-iris/xair-api-python#6]
Hi there,
First so many thanks for this lib.

I try to receive MIDI input from an external controller fader, then transform and forward events to the MR18 through OSC api call.
Sadly, api calls don't allow to forward faders event to MR18 in real time, occuring a big latency.

Is there a way to forward OSC events in real-time ?
Thanks in advance

**Comment by onyx-and-iris** [comment]
Hi. 

You can try [adjusting the delay kwarg](https://github.com/onyx-and-iris/xair-api-python?tab=readme-ov-file#xair_apiconnectkind_id-ipip-delaydelay), it defaults to 0.02 but as noted in the README it can be safely reduced for wired connections. You may need to experiment with this though, in the included test suites I was able to get stable passes at 0.008.

Looking at the base class perhaps we can remove `time.sleep(self._delay)` from the {XAirRemote}.send() method entirely and just move it into query. I suspect that's causing the issue you experience. The delay variable only exists to ensure the mixer updates values before sending them back (for the getters).

I'll need to investigate this.

**Comment by rey0bs** [comment]
Hi,

Thanks a lot for your quick reply.
When I remove the `sleep` instruction it is fine, and when I reduce the delay to 0.008 it works perfectly.

Maybe it could be a good strategy to add the `sleep` instruction before "query" calls, instead of after every "send" calls. Or add a delay between a "send" and a "query" to ensure the mixer updates values.
What about adding an options (like the delay kwarg) to adjust the "latency" if needed ?

Thx

**Comment by rey0bs** [comment]
Hi,

Thanks a lot for your quick reply.
Yes, you're right, when I set the delay to 0, the latency disappears and it works perfectly. 0.008 still insufficient to run in a real-time feeling.

As you said, it could be a good strategy to move the `sleep` instruction into "query" method. Or maybe move this delay between a "send" and a "query" call to ensure the mixer updates values ?

In my case, I only need to send "set" instructions, so I think I don't need any delay.

Thx

**Comment by onyx-and-iris** [comment]
Yes I think that would be the correct approach. I will tackle this and channel sends for mixbuses in the coming days.

**Comment by rey0bs** [comment]
Channel sends are working well, i.e using `mixer.send("/ch/01/mix/07/level", 0.7)` for FX1
